version: '3.9'

services:
  # 1) PostgreSQL
  db:
    image: postgres:14
    container_name: avito_postgres
    restart: unless-stopped
    env_file:
      - backend/.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  # 2) Redis (брокер сообщений для Celery и Channels)
  redis:
    image: redis:7
    container_name: avito_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  # 3) Django + Daphne (ASGI)
  backend:
    container_name: avito_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      daphne -b 0.0.0.0 -p 8000 config.asgi:application
      "
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: unless-stopped
    env_file:
      - backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - USE_S3=TRUE
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}

  # 4) Celery Worker
  celery:
    container_name: avito_celery
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=INFO
    volumes:
      - ./backend:/backend
    depends_on:
      - backend
      - redis
    restart: unless-stopped
    env_file:
      - backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}

  # 5) Celery Beat (планировщик периодических задач)
  celery-beat:
    container_name: avito_celery_beat
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A config beat --loglevel=INFO
    volumes:
      - ./backend:/backend
    depends_on:
      - backend
      - redis
    restart: unless-stopped
    env_file:
      - backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}

  # 6) Next.js Frontend
  frontend:
    container_name: avito_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    env_file:
      - frontend/.env

# Общие именованные тома
volumes:
  postgres_data:
  static_volume:
  media_volume: 