release: python manage.py migrate
# web: daphne config.asgi:application --port $PORT --bind 0.0.0.0 -v2
web: daphne -b 0.0.0.0 -p 8000 config.asgi:application
celery: celery -A config.celery worker -l info
celerybeat: celery -A config beat -l INFO 
celeryworker2: celery -A config.celery worker & celery -A config beat -l INFO & wait -n